CREATE TABLE orders (
                        id           UUID           NOT NULL,
                        customer_id  UUID           NOT NULL,
                        status       VARCHAR(32)    NOT NULL,
                        total_amount NUMERIC(12, 2) NOT NULL,
                        created_at   TIMESTAMPTZ    NOT NULL,
                        updated_at   TIMESTAMPTZ    NOT NULL,
                        version      BIGINT         NOT NULL,
                        CONSTRAINT pk_orders PRIMARY KEY (id),
                        CONSTRAINT ck_orders_status CHECK (status IN
                                                           ('CREATED', 'PAYMENT_PENDING', 'PAID', 'INVENTORY_PENDING', 'CONFIRMED', 'CANCELLED')),
                        CONSTRAINT ck_orders_total_nonnegative CHECK (total_amount >= 0)
);

CREATE TABLE order_items (
                             id         BIGINT GENERATED BY DEFAULT AS IDENTITY,
                             order_id   UUID           NOT NULL,
                             sku        VARCHAR(255)   NOT NULL,
                             quantity   INTEGER        NOT NULL,
                             unit_price NUMERIC(12, 2) NOT NULL,
                             CONSTRAINT pk_order_items PRIMARY KEY (id),
                             CONSTRAINT fk_order_items_order FOREIGN KEY (order_id) REFERENCES orders (id),
                             CONSTRAINT ck_order_items_quantity CHECK (quantity > 0),
                             CONSTRAINT ck_order_items_unit_price CHECK (unit_price > 0)
);

CREATE INDEX idx_orders_customer_id ON orders (customer_id);
CREATE INDEX idx_orders_status ON orders (status);
CREATE INDEX idx_order_items_order_id ON order_items (order_id);